version: "2"
run:
  build-tags:
    - e2e
linters:
  default: none
  enable:
    - bodyclose
    - depguard
    - errcheck
    - errorlint
    - gochecknoinits
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/davecgh/go-spew
            - pkg: log
            - pkg: github.com/pkg/errors
              desc: use Go stdlib errors instead
            - pkg: github.com/cenkalti/backof[f]
              desc: use github.com/cenkalti/backoff/v4 instead
            - pkg: gotest.tools/assert
              desc: use gotest.tools/v3/assert instead
            - pkg: gotest.tools/skip
              desc: use gotest.tools/v3/skip instead
            - pkg: gotest.tools/assert/cmp
              desc: use gotest.tools/v3/assert/cmp instead
            - pkg: gotest.tools/env
              desc: use gotest.tools/v3/env instead
            - pkg: gotest.tools/fs
              desc: use gotest.tools/v3/fs instead
            - pkg: gotest.tools/golden
              desc: use gotest.tools/v3/golden instead
            - pkg: gotest.tools/icmd
              desc: use gotest.tools/v3/icmd instead
            - pkg: gotest.tools/poll
              desc: use gotest.tools/v3/poll instead
    dupl:
      threshold: 100
    goconst:
      min-len: 6
      min-occurrences: 8
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 120
    nakedret:
      max-func-lines: 0
  exclusions:
    generated: lax
    rules:
      - linters:
          - gosec
        text: G104
      - linters:
          - staticcheck
        text: SA5001
      - linters:
          - staticcheck
        path: _test\.go
        text: SA1019
      - linters:
          - staticcheck
        path: testing
        text: SA1019
      - linters:
          - golint
        text: should have( a package)? comment
      - linters:
          - lll
        source: https?://
      - linters:
          - lll
        source: '"message":'
      - linters:
          - errcheck
        source: ^\s*defer .*\.Close(.*)$
      - linters:
          - ineffassign
        source: ^\s*ctx.*=.*$
      - linters:
          - staticcheck
        source: ^\s*ctx.*=.*$
      - linters:
          - funlen
        text: ^Function 'Test.*
      - linters:
          - staticcheck
        text: ST1000
      - linters:
          - unparam
        path: _test\.go
      - linters:
          - gochecknoinits
        path: /rootcerts
      - linters:
          - gosec
        path: /rootcerts
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/circleci/ex
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
